Default testalert to never
PagerBuddy/Server pull request #61
Opened 2022-09-25 20:20 UTC by maxbartunik

Currently all alerts set to default values are taken as testalerts on a Sunday. This PR fixes the issue and defaults to no testalert.

2022-09-29 12:14 UTC, keszocze commented
From neither the description nor the code changes I have any idea, what this request is about.

2022-09-29 12:17 UTC, maxbartunik commented
> From neither the description nor the code changes I have any idea, what this request is about.

Sorry, thiw was a middle of the night thing. We currently have a bug: As "Schleifen" default to testday 0, testtime 0 to 0, all ZVEIs, that do not have a testperiod set are detected as "test alerts" all day on sundays. This is counter intuitive (i.e. wrong). Instead alert with no testperiod set should never be detected as "test alert". This is fixed by this PR.

2022-09-29 12:18 UTC, maxbartunik commented
The changes are:
- change default test day to -1 (i.e. never)
- allow -1 as parameter in test cases etc.

2022-09-29 12:38 UTC, keszocze commented
> The changes are:
> 
>     * change default test day to -1 (i.e. never)
> 
>     * allow -1 as parameter in test cases etc.

I really hate "magic numbers" such as `-1` meaning something. I always prefer something like an optional in such a case. But I think that is I fight I already lost $\Rightarrow$ accepting

2022-09-29 12:41 UTC, maxbartunik commented
> > The changes are:
> > ```
> > * change default test day to -1 (i.e. never)
> > 
> > * allow -1 as parameter in test cases etc.
> > ```
> 
> I really hate "magic numbers" such as `-1` meaning something. I always prefer something like an optional in such a case. But I think that is I fight I already lost ⇒ accepting
> 
> (you do have to change the error message though...)

true - I am trying but frequently fall back ;)

2022-09-29 12:42 UTC, keszocze requested changes

2022-09-29 12:42 UTC, keszocze commented on src/model/zvei.mjs
>              throw new Error(`Test day '${test_day}' is not from the range [0,6]`);
As you allow `-1` to be a valid date, the error message should reflect this.
```suggestion
            throw new Error(`Test day '${test_day}' is not from the range [-1,6]`);
```

Btw, are you sure that `-1` is not the second to last day of the week? I mean, JS does weird things with dates.

2022-09-30 12:43 UTC, maxbartunik commented
> > > The changes are:
> > > ```
> > > * change default test day to -1 (i.e. never)
> > > 
> > > * allow -1 as parameter in test cases etc.
> > > ```
> > 
> > 
> > I really hate "magic numbers" such as `-1` meaning something. I always prefer something like an optional in such a case. But I think that is I fight I already lost ⇒ accepting
> > (you do have to change the error message though...)
> 
> true - I am trying but frequently fall back ;)

I will leave this for v2...

2022-09-30 13:44 UTC, merged